name: own_delivery
description: OwnDelivery Customer App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Firebase
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1

  #Icons
  cupertino_icons: ^1.0.5

  #URL Launcher
  url_launcher: ^6.1.7

  date_utils: ^0.2.0

  #Mapbox
  mapbox_gl: ^0.16.0
  mapbox_gl_web: ^0.16.0
  mapbox_search: ^3.0.1+2

  retrofit: '>=3.0.0 <4.0.0'
  dio: ^4.0.6
  json_annotation: ^4.7.0
  firebase_analytics: ^10.1.0

  html: ^0.15.1
  webviewx: ^0.2.1

  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0'
  json_serializable: '>4.4.0'

flutter:
  uses-material-design: true

  assets:
    - env
    - assets/
